---
title: 
output: 
  word_document
    reference_docx: styles-ref.docx
---

```{r, echo=FALSE}
suppressWarnings(suppressPackageStartupMessages(library(ggplot2)))
suppressWarnings(suppressPackageStartupMessages(library(dplyr)))
suppressWarnings(suppressPackageStartupMessages(library(leaflet)))
suppressWarnings(suppressPackageStartupMessages(library(DT)))
suppressWarnings(suppressPackageStartupMessages(library(stringr)))
library(knitr)
library(markdown)
library(rmarkdown)
```

```{r, include=FALSE}

dbns <- cte_data2[rownames(cte_data2)==dbn,]
school_name <- dbns$Location.Name
address <- dbns$Primary.Address
city <- dbns$City
nta <- dbns$NTA_Name
district <- dbns$Geographical.District.Code

principal_name <- dbns$Principal.Name
principal_title <- dbns$Principal.Title
principal_contact <- dbns$Principal.Phone.Number

bfsc_dir_name <- dbns$BFSC.Director.Name
bfsc_dir_title <- dbns$BFSC.Director.Title
bfsc_dir_phone <- dbns$BFSC.Director.Phone

grades <- dbns$Grades.Final

```
# `r school_name`
Run on: `r Sys.Date()`
DBN: `r dbn`

## Location and Contacts

### Location: 
  
`r address` , `r city`, `r nta`
    
District `r district`
     
### Principal

Name: `r principal_name` 
    
Title: `r principal_title` 
    
Contact: `r principal_contact` 
    
### Borough Field Support Center

Name: `r bfsc_dir_name` 
    
Title: `r bfsc_dir_title` 
    
Contact: `r bfsc_dir_phone` 
    
### Grades 
`r grades`
    
    

```{r, echo=FALSE}

kable(dbns[c(1:3)])

```

<!-- tbl_df(dbns) -->
<!-- #  -->
<!-- # # create daily data  -->
<!-- # x <- sample(1:10, 1) -->
<!-- #  -->
<!-- # cars <- do.call("rbind", replicate(x, cars, simplify = FALSE)) -->
<!-- #  -->
<!-- # cars$lat <- sapply(rownames(cars), function(x) round(runif(1, 30, 46), 3)) -->
<!-- # cars$lon <- sapply(rownames(cars), function(x) round(runif(1, -115, -80),3)) -->

```

Today is `r Sys.Date()`.  

Today we sold `r nrow(cars)` `r car`. 

<br><br>

<!-- Today we sold cars to people in the following locations:  -->
<!-- ```{r, echo=FALSE} -->
<!-- # map of cars sold -->
<!-- leaflet(cars) %>% -->
<!--   addTiles() %>% -->
<!--   setView(-93.65, 42.0285, zoom = 3) %>% -->
<!--   addCircles(cars$lon, cars$lat)  -->
<!-- ``` -->

<!-- <br><br> -->

<!-- Here is a data table of the cars we sold.  -->
<!-- ```{r, echo=FALSE} -->
<!-- # data table of cars sold  -->
<!-- datatable(cars[,c(1:2, 12:13)]) -->
<!-- ``` -->

<!-- <br><br> -->

<!-- Here is a plot of mpg vs. weight for the sold cars:  -->
<!-- ```{r, echo=FALSE} -->

<!-- # plot  -->
<!-- ggplot(cars, aes(mpg, wt)) + geom_point(position = position_jitter(w = 0.1, h = 0.1)) + stat_smooth(method="lm", se=TRUE) -->

<!-- ``` -->

